### ISSUE TITLE
Should specify install visual studio 2017 and c++ during cargo install

### ISSUE THREAD

**Issue by chisNaN** [input-output-hk/cardano-byron-cli#105]
Hello. Once again i wanted to play with cardano-cli on **WINDOWS 10** (this time)
with : 

- cargo 1.33.0 (f099fe94b 2019-02-12)
- rustc 1.33.0 (2aa4c46cf 2019-02-28)

I had the following FATAL error (stopping all compilations) at first

`please ensure that VS 2013, VS 2015 or VS 2017 was installed with the Visual C++ option`

Maybe somewhere in the process install of the README could be mentionned the requirement of these softwares 

[Github solution](https://github.com/rust-lang/rustup.rs/issues/1003)

I had no problem with installing the 2017 version + the **WINDOWS UCRT SDK extension**

**Comment by mzabaluev** [comment]
To me it looks like peculiarities of the rust target platform. We should not try repeat all the Windows-specific rustup guidance in our README, as this should be common to all Rust projects and may change with time.

**Comment by chisNaN** [comment]
ok
