### ISSUE TITLE
Build error "could not find `parse` in `genesisdata`"

### ISSUE THREAD

**Issue by ItFlyingStart** [input-output-hk/cardano-byron-cli#107]
I got the next build error from the master version "20310a75386b0d0dc100902f9c87956be199dffe".

`rustup update` and `cargo update` haven't resolved this build issue. I can build "rust-cardano" without any issue.

> Compiling cardano-cli v1.0.1 (C:\Git\Blockchain\IOHK\cardano-cli)
error[E0433]: failed to resolve: could not find `parse` in `genesisdata`
   --> src\blockchain\mod.rs:129:41
    |
129 |         let genesis_data = genesisdata::parse::parse(fs);
    |                                         ^^^^^ could not find `parse` in `genesisdata`

> error[E0433]: failed to resolve: could not find `parse` in `genesisdata`
  --> src\debug\mod.rs:60:31
   |
60 |     print!("{}", genesisdata::parse::canonicalize_json(json.as_bytes()));
   |                               ^^^^^ could not find `parse` in `genesisdata`

> warning: use of deprecated item 'cardano_storage::iter::Iter'
   --> src\blockchain\mod.rs:256:26
    |
256 |     ) -> storage::Result<storage::iter::Iter<'a>> {
    |                          ^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: #[warn(deprecated)] on by default

![image](https://user-images.githubusercontent.com/5562995/53718919-e61bb680-3e5c-11e9-924c-b1dae71d4076.png)

**Comment by NicolasDP** [comment]
I am sorry to hear that: can you check your `git submodule` is at the appropriate version pinned by the current revision at `master` branch ?

You can see that looking at `git status` you will see that `cardano-deps` is no longer the appropriate value. You can fix this with `git submodule update`.

**Comment by ItFlyingStart** [comment]
Thanks for your quick reply Nicolas. Your solution works.
