### ISSUE TITLE
Several sync duplicate UTxO credits without warning or fatal errors

### ISSUE THREAD

**Issue by chisNaN** [input-output-hk/cardano-byron-cli#108]
Hello.
I wanted to play a little with cardano-cli on both macOS and windows 10.
(I pulled the master branch approx 10 days ago)
I am commenting this issue because I managed after syncing several times a wallet
**to generate a DOUBLE UTXO CREDIT
which gives me a wrong final balance.**
Indeed if i detach and attach the wallet to the blockchain
and finally resync the wallet
last utxo credit is not duplicated in the log.
Contrarily to @HM999 I did not have any kind of fatal errors
But it's quite annoying having to make [detach, attach and syncing] operations again to be in a "correct" state.

What would you suggest?
Thanks
<img width="674" alt="duplicated-credit-cardano-cli" src="https://user-images.githubusercontent.com/2439389/54083117-f1b92280-431f-11e9-9cbf-89f727fa4023.PNG">
<img width="674" alt="status-wallet" src="https://user-images.githubusercontent.com/2439389/54083118-f251b900-431f-11e9-8995-af68f40c60d8.PNG">
<img width="674" alt="utxos" src="https://user-images.githubusercontent.com/2439389/54083119-f251b900-431f-11e9-9c13-5ed1c7ccff36.png">

**Comment by NicolasDP** [comment]
Which version are you utilising ?

**Comment by chisNaN** [comment]
Hello @NicolasDP thanks for your reactivity
Here's my config:

- Windows 10
- cardano-cli 1.0.1
- rustc 1.33.0 (2aa4c46cf 2019-02-28)
- cargo 1.33.0 (f099fe94b 2019-02-12)

(it's probable i did not have the same problem on macOS)

**Comment by chisNaN** [comment]
@NicolasDP what i can try to do is to see
how many syncs in a row I have to do to provoke this duplicate credit utxos.
It was not that much <10
