### ISSUE TITLE
the LOG is not found utxo

### ISSUE THREAD

**Issue by xulizhe** [input-output-hk/cardano-byron-cli#114]
cardano-cli blockchain pull mainnet
cardano-cli wallet sync
the LOG is not found utxo?what's happen?
the explorer can find txid

**Comment by NicolasDP** [comment]
did you generate multiple addresses (more than 20) ? It seems there is an issue introduce with a recent change in the core that may be the source of that. we are investigating.

In the meanwhile can you provide a better description of the problem and mean to reproduce it (how many addresses you have generated etc.)

**Comment by xulizhe** [comment]
yes I am the problem provider

**Comment by rdlrt** [comment]
I will give a try to describe the issue he faces. He has created/saved 100 addresses (with addr idx 0-99) attached to a single account. Some of these addresses have now received few ADA (eg: address with address idx 60), but he is not able to see this address in utxo or statement.
Can be replicated by sending an amount to an address with Address with index 60 after sending to address with idx 1 for example.

Edit: Ruslan explained how this would be violation of BIP44 standards - going beyond the default gap of 20.

**Comment by NicolasDP** [comment]
ha yes, thanks. The recent PR (#115 ) will help you with this. We have implemented the protocol BIP44 as is for the address recovery. The configuration from the environment is only a work around. There is no real solution to this except: make sure you have less big gaps.
