### ISSUE TITLE
tx-bytes: 11132

### ISSUE THREAD

**Issue by xulizhe** [input-output-hk/cardano-byron-cli#119]
I created the transaction and then added a lot of input.
when i execute cardano-cli transaction status 4tHCaf,i found tx-bytes is 11131.
![image](https://user-images.githubusercontent.com/15604297/58873617-4d196780-86f9-11e9-80da-a0ed49cec939.png)
then execute cardano-cli transaction finalize 4tHCaf and cardano-cli transaction sign 4tHCaf
but when i execute cardano-cli transaction send 4tHCaf mainnet,i got a error

![image](https://user-images.githubusercontent.com/15604297/58873700-82be5080-86f9-11e9-8f0c-de5b6af4a8a4.png)

**Comment by rdlrt** [comment]
Issue was reported on  https://t.me/CardanoCommunityTechSupport :
- Problem was with few specific tx with lot of utxos as input.
- Checked how the tx was being generated, the inputs were added manually via "add-input".
- Explained how that could be the potential issue and the size of transaction could go very high , and hence, the fee for the transaction.
- Asked to test using "input-select" option instead and the different options (select-largest-first v/s select-exact-inputs). In most cases, this should automatically reduce the size of the transaction.
