### ISSUE TITLE
The cardano-cli can run in the background as server?

### ISSUE THREAD

**Issue by Victoryfan** [input-output-hk/cardano-byron-cli#121]
Hi, who can answer my question? Does the cardano-cli run as a server in the background like a node to sync blocks?

**Comment by NicolasDP** [comment]
It is not possible to do that at the moment. It was mainly designed to run incremental operation on one or multiple blockchain.

1. user decides when to update the blockchain;
2. user decides when to sync the wallet against the associated blockchain;

it is still fairly manual and atomic : 1 command => 1 action.
