### ISSUE TITLE
"cardano-cli blockchain pull mainnet" crashes, BlockNotFound error

### ISSUE THREAD

**Issue by rs-blashyrkh** [input-output-hk/cardano-byron-cli#123]
> $ ./cardano-cli blockchain pull mainnet
> fetching blocks from peer: iohk-hosts
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: BlockNotFound([52, 150, 198, 74, 97, 203, 180, 101, 112, 95, 90, 171, 83, 61, 6, 226, 65, 47, 184, 219, 199, 129, 5, 207, 244, 60, 58, 222, 198, 219, 2, 206])', src/libcore/result.rs:1009:5
> note: Run with `RUST_BACKTRACE=1` for a backtrace.

I tried to remove local "mainnet" blockchain completely and fetch it again. First fetch succeeds, the following ones fail with the error above.

cardano-cli version: e2dd58e (master branch)
rustc 1.37.0
gentoo linux x86_64, kernel 4.19.23, glibc 2.29-r7.

**Comment by brenoluz** [comment]
I am with same problem

**Comment by rs-blashyrkh** [comment]
It shows different block now: BlockNotFound([131, 157, 251, 41, 182, 84, 94, 116, 186, 142, 174, 166, 27, 82, 115, 172, 101, 182, 178, 142, 59, 200, 54, 180, 71, 147, 139, 236, 34, 129, 133, 191]). I suppose it's always a block from the latest epoch.
