### ISSUE TITLE
Connection to mainnet impossible

### ISSUE THREAD

**Issue by ml31415** [input-output-hk/cardano-byron-cli#127]
Whatever I try, the client seems unable to connect to the mainnet hosts. Recent master, recent rustc. Is the provided config outdated?

When I try to use the servers provided from `https://hydra.iohk.io/build/5047936/download/1/mainnet-topology.json` instead, the timeouts don't show up anymore, but the connection is still impossible. Any ideas?
```
$# cardano-cli blockchain pull mainnet
fetching blocks from peer: iohk-hosts
 WARN 2020-12-04T13:26:49Z: exe_common::network::native: connection peer `iohk-hosts' address 52.198.18.45:3000 timed out, ignoring for now.
 WARN 2020-12-04T13:27:19Z: exe_common::network::native: connection peer `iohk-hosts' address 13.112.180.247:3000 timed out, ignoring for now.
 WARN 2020-12-04T13:27:49Z: exe_common::network::native: connection peer `iohk-hosts' address 13.228.253.150:3000 timed out, ignoring for now.
```

**Comment by nix4me** [comment]
I'm also wondering about this iohk-hosts timeout issue.
