### ISSUE TITLE
cardano-cli minimum fees calculation for --tx-in-count=2 not correct

### ISSUE THREAD

**Issue by nilaysaha** [input-output-hk/cardano-byron-cli#128]
I was working on calculation of minimum fees for committing a transaction.

['/home/testuser/.cabal/bin/cardano-cli', 'transaction', 'calculate-min-fee', '--tx-body-file', './kaddr/tx.raw', '--witness-count', '0', '--tx-in-count', '2', '--tx-out-count', '1', '--byron-witness-count', '0', '--mainnet', '--protocol-params-file', './kaddr/protocol.json'] 

output is:170253 Lovelace

based on :

{
    "blockNo": 5155136,
    "headerHash": "0b403be0dedab54ecfa5dfaaf076f9e00df92b9b827d22d6628a2f2b5acdd427",
    "slotNo": 17989175
}

ttl:17990375

At the end the transaction being built is:

['/home/testuser/.cabal/bin/cardano-cli', 'transaction', 'build-raw', '--allegra-era', '--tx-out', '<payment_addr>+8497048547', '--ttl', '17990375', '--fee', '17990375', '--out-file', './kaddr_node/pool_trans.raw', '--certificate-file', './kaddr_node/pool_registration.cert', '--certificate-file', './kaddr_node/pool_delegation.cert', '--tx-in', '<txhash_1>#0', '--tx-in', '<txhash_2>#0']

And it fails when submitting with error:

Shelley command failed: transaction submit  Error: Error while submitting tx: ApplyTxError [LedgerFailure (UtxowFailure (UtxoFailure (FeeTooSmallUTxO (Coin 192121) (Coin 170253))))]. 

So now I changed the minimum amount to: 

minimum fee calc: 192121

And transaction succeeded. 

Question: Why was the minium amount calculation not correct for the above transaction ? I tried with support and they were not able to help.

**Comment by rdlrt** [comment]
This is rust based cardano-cli, completely different to what you use.

Thus, it is unrelated to the usage query (wrong number of witness count in your calcuate fee command) as already explained in telegram groups.
