### ISSUE TITLE
Offline Transactions

### ISSUE THREAD

**Issue by johnshearing** [input-output-hk/cardano-byron-cli#27]
Using Web3 for Ethereum at the command line it is possible to create and send offline transactions from an airgapped computer without syncing to the blockchain.

[This video shows how to create the offline transaction on an airgapped device using the CLI:](https://youtu.be/-5LhwoCcjp0?t=9m35s)

[This video shows how to send the offline transaction to the blockchain without needing to sync up or even have a copy of the blockchain.](https://www.youtube.com/watch?v=BFEzWYFZ7wA&list=PLV1JDFUtrXpFh85G-Ddyy2kLSafaB9biQ&index=6)

[This video shows an airgapped device created for making offline transactions.](https://www.youtube.com/watch?v=_vA4tTLdL2M)

I need this level of security before I can seriously invest in Cardano.
Can I create and send offline transactions from an airgapped device using the Cardano-CLI?
Thanks, John

**Comment by vincenthz** [comment]
yes, it's not yet fully documented (and reasonably, brand new too, use with care), but by design of the CLI, you can export/import a transaction being created at any stage, so you can:

* on A: create your transaction on a machine A (add inputs, outputs, etc..)
* on A: export it, "send" the file to a machine B (disconnected from network, but holding the keys)
* on B: import the file from a usb stick, etc...
* on B: sign it
* on B: export it, send the file to a machine C
* on C: import the file, sent it to network

https://github.com/input-output-hk/cardano-cli/blob/master/USAGE.md

**Comment by johnshearing** [comment]
Hi vincenthz,
Thanks for the help.
I think this removes one of the two biggest blocks preventing Cardano from dominating the crypto space.

The other one is having the ability to generate our own private keys by flipping a coin or by some other method that we can know for certain is truly random. Perhaps it is possible to do this now but I will ask about it in a separate post.

I see there are a few videos on how to use the Cardano-CLI. 
Would you please consider doing a video demonstration on how to make and send an offline transaction using an airgapped machine.
Thanks, John

**Comment by vincenthz** [comment]
I'll transmit the request to our tutorial/video expert, no promises, but it's a good idea !

Not sure about flipping the coin private key, it's not technically hard to offer something here, but what exactly would you like to see ? purely speaking, our private keys are 96 bytes, that means for "perfect entropy" we need to ask for 768 coin flips.

Would you settle for something that ask for less and does a "stretch" ?

I've seen an article talking about coin flipping in the past, but I don't remember exactly the details. If you have a specific technic (with technical details) in mind, we're happy to go and have a read.

**Comment by johnshearing** [comment]
Thanks Vincent,
I am going to copy your comments about coin flipping into the newly created issue about that and continue the conversation from there.
Thanks, John

**Comment by purplecity** [comment]
there has a problem. 

when machine  A create a transaction. A should add-input but add input need use command cardano-cli wallet utxo XXX to get the utxo of address. it's also mean A has the private key of XXX.  

I don't want the private key  holding in A. I Just want use private key to sign the transaction. at machine B. 


is there has any way to know the  utxo of one address without of private key?
