### ISSUE TITLE
Generate Keys by Flipping Coin or By Method Known is Truly Random And Unhackable

### ISSUE THREAD

**Issue by johnshearing** [input-output-hk/cardano-byron-cli#29]
Hi All,
Crazy as it may sound - I generate my private keys on the Ethereum block chain by flipping a coin. 

This way even if someone were to place malware into my client which will produce a predictable private key my funds can not be stolen by this attack.

Before I can seriously invest in Cardano, I must be able to use my own private key which has been produced by some manner that is known to be truly random and unhackable. 

Is it possible using the Cardano-CLI to create a wallet from a private key which has been generated by some offline method such as flipping a coin?

Thanks, John

**Comment by johnshearing** [comment]
Vincent Hanquez a member of Input Output was kind enough to leave the following reply when I first mentioned coin flipping while posting an issue about offline transactions.
...
Not sure about flipping the coin private key, it's not technically hard to offer something here, but what exactly would you like to see ? purely speaking, our private keys are 96 bytes, that means for "perfect entropy" we need to ask for 768 coin flips.

Would you settle for something that ask for less and does a "stretch" ?

I've seen an article talking about coin flipping in the past, but I don't remember exactly the details. If you have a specific technic (with technical details) in mind, we're happy to go and have a read.

**Comment by johnshearing** [comment]
Please let me explain what I do when making a new Ethereum account so you will understand what I need in order to feel safe enough to invest in Cardano. For all I know, the Cardano-CLI can already facilitate the following. That's what I am asking.

I view the generation of keys by a wallet as a central point of vulnerability. 
So I generate my own private key by flipping a coin. 
Ethereum keys are 64 hexadecimal numbers each of which can be represented by 4 binary digits. 
So I flip a coin 4 times to get each number. 
I let heads represent 1 and tails represent zero. 
So if I flip tails, tails, tails, tails, then my first hexadecimal number will be a 0. 
If I then flip heads, heads, heads, heads, then my next hexadecimal number will be an F. 
Tails, heads, tails, heads, would represent a hexadecimal 5.
I keep doing this until I have all 64 hexadecimal numbers.
I use this number as my private key and run a function on this number at the command line to get my public address.
Now I have my public/private key pair which can be used to make transactions at the command line.
[This video shows how to create a public/private key pair at the command line](https://www.youtube.com/watch?v=YWoBeoTUrYM&list=PLV1JDFUtrXpFh85G-Ddyy2kLSafaB9biQ&index=2)
[This video shows how raw private keys are used to make transactions at the command line](https://youtu.be/-5LhwoCcjp0?t=9m35s)

Vincent writes:
>purely speaking, our private keys are 96 bytes, that means for "perfect entropy" we need to ask for 768 coin flips.<

I don't want the wallet to ask for coin flips. Rather what I want is the ability sign transactions by entering a private key that I have generated on my own by flipping a coin or by some other decentralized process that is known to be completely random. 

I looked over the command line documentations and can't find anything that lets you see your own private key nor do I see any command that allows you to make a wallet by entering a private key arrived at by flipping a coin or by some other decentralized process.

Am I missing it or this the functionality not there.
Thanks for your help,
John

**Comment by vincenthz** [comment]
thanks @johnshearing for describing the method in details. I'm happy to add a way to initialize a new wallet root private key in hexadecimal directly, with a possible disclaimer to outline the risks of not doing this properly.

Technically right now, you could abuse the `wallet recover` to do almost that if you're ok with the stretching phase which take a 16 to 32 bytes "entropy" and convert it to a 96 bytes key. you would have to convert your hexadecimal string decided by coin flipping into 12 to 24 word mnemnonic sentence (easy, any off the shelves BIP39 library could do that) and enter that in the CLI.

1. coin flip `16 * 8` to `32 * 8` times writing down the hexadecimal result
2. use bip39 to convert to a mnemnonic sentences (12 to 24 words), for example through you can enter your own entropy in hexadecimal https://iancoleman.io/bip39/ + click show entropy. Of course if you insist in doing your own random generation, then using an online service is probably not going to fly, but you can find offline version of this by searching a bit
3. use `wallet recover` with the mnemnonic sentence

Now, if you really want to input the private key directly we're using in the wallet, we're talking about are 192 hexadecimal numbers, 3 times greater than the ethereum keys mentioned above.

As a side note on your method, I would suggest moving to a 16 faces dice (D16) for each hexadecimal digits, which would greatly improve efficiency of the process and possibly make it less tedious (for a full private key "only" 192 throws compare to 768 coin flips)

**Comment by johnshearing** [comment]
Hi @vincenthz
If I could cut and paste a 192 character hexadecimal private key into the Cardano-CLI for signing offline transactions and for creating new wallets then I can produce an inexpensive, super secure, open source, airgapped computer for Cardano as I have done for Ethereum.

The entire Linux operating system and all of the data is protected by LUKS full disk encryption.
So it can be used to secure any type of private digital information.
![laptop](https://user-images.githubusercontent.com/22293905/46567731-0115e900-c906-11e8-9011-4460c3db6db5.jpg)
The SD card which holds the data and OS can be easily cloned for backup with encryption intact.

The transparent case allows you to see if anything has been tampered with and tamper resistant seals indicate if the case has been opened. This mitigates a Maid in the Middle attack.
![packedup](https://user-images.githubusercontent.com/22293905/46567721-b5fbd600-c905-11e8-98cd-97a12b046bed.jpg)

[Keys are passed in using qr-codes and offline transactions are passed out using qr-codes.](https://youtu.be/_vA4tTLdL2M)
So there is no need to plug anything into the device and no need for WiFi. 
The device is safe from online hackers.

[Entire PGP encrypted files are passed in and out using videos which flash one qr-code for each line of the file.](https://github.com/johnshearing/Airgapped_Encrypted_Messaging)
This photo shows the latest version configured to pass an encrypted text file to a mobile phone by flashing a series of QR-Codes. Nothing gets plugged in to the computer and no radios are installed.
![passingqr_code1](https://user-images.githubusercontent.com/22293905/46566401-ad96a180-c8eb-11e8-859b-cfa459b21874.jpg)
This is another reason for having a transparent modular design.

I can easily fit the device with a mechanical means for generating and inputting truly random numbers.
And once the number is in the machine it could be a simple matter to cut and paste it when creating offline transactions at the command line.

Security has always been the issue keeping the masses from adopting cryptocurrency at the institutional level. I think this device solves the problem and it works well when interacting with the Ethereum block chain. With your help, it can work with Cardano too.

Individuals need fully decentralized control over the generation of private keys and we need an easy way to pass offline transactions to the block chain.

I can't wait to see what you are going to make for the Cardano community.
I can't wait to see how the world responds.
Thanks, John

**Comment by Jotunn-com** [comment]
I want to see this sort of innovation available to Cardano users.

The purity of coin/dice is hard to beat, purity aside, when I build one though it will have an infinite noise TRNG, likely this one: https://github.com/waywardgeek/infnoise

An Airgapped GPG Encrypted Cardano using QR-Coded Video, I can't wait.
