### ISSUE TITLE
cargo install error

### ISSUE THREAD

**Issue by purplecity** [input-output-hk/cardano-byron-cli#41]
warning: value assigned to `out_total_min` is never read
   --> cardano-deps/cardano/src/txbuild.rs:149:21
    |
149 |                 let mut out_total_min = Coin::zero();
    |                     ^^^^^^^^^^^^^^^^^
    |
    = note: #[warn(unused_assignments)] on by default

   Compiling tokio-core v0.1.17
warning: unused `std::result::Result` which must be used
   --> cardano-deps/cardano/src/block/verify_chain.rs:282:9
    |
282 |         mem::replace(res, err);
    |         ^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: #[warn(unused_must_use)] on by default

   Compiling tokio-proto v0.1.1
   Compiling hyper v0.11.27
   Compiling protocol v0.1.0 (file:///home/ec2-user/cardano-cli/cardano-deps/protocol)
   Compiling cardano-storage v0.1.0 (file:///home/ec2-user/cardano-cli/cardano-deps/storage)
   Compiling exe-common v0.1.0 (file:///home/ec2-user/cardano-cli/cardano-deps/exe-common)
error[E0658]: use of unstable library feature 'assoc_unix_epoch' (see issue #49502)
  --> cardano-deps/exe-common/src/parse_genesis_data.rs:36:9
   |
36 |         SystemTime::UNIX_EPOCH + unix_displacement
   |         ^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: failed to compile `cardano-cli v1.0.0-alpha2 (file:///home/ec2-user/cardano-cli)`, intermediate artifacts can be found at `/home/ec2-user/cardano-cli/target`

Caused by:
  Could not compile `exe-common`.

To learn more, run the command again with --verbose.

**Comment by NicolasDP** [comment]
that's interesting, what version of the compiler are you using?

**Comment by mzabaluev** [comment]
The UNIX_EPOCH constant is stable since rustc 1.28.0. Which rustc version are you using?

**Comment by purplecity** [comment]
> that's interesting, what version of the compiler are you using?

sorry it is unable to repeat.  I installed it several times。 


@mzabaluev  I remember it is 1.28.0

@NicolasDP   I am sure althought I use most new rust version and result is CLI installed finally, but There will be warnings during installation ,may be u can try it (ubuntu 16.04) 。like this 
<img width="989" alt="wechatimg4" src="https://user-images.githubusercontent.com/38914615/47850733-3cc2a680-de11-11e8-9dec-bf66b119d775.png">

**Comment by purplecity** [comment]
sorry it is unable to repeat. I installed it several times。

@mzabaluev  it is 1.27.0

@NicolasDP I am sure althought I use most new rust version and result is CLI installed finally, but There will be warnings during installation ,may be u can try it (ubuntu 16.04) 。like this

<img width="989" alt="wechatimg4" src="https://user-images.githubusercontent.com/38914615/47852993-5adfd500-de18-11e8-8aa9-9a2e8f772cb9.png">
