### ISSUE TITLE
wallet detach

### ISSUE THREAD

**Issue by Syr3mas** [input-output-hk/cardano-byron-cli#50]
Wrong success message after using wallet detach.

- cardano-cli wallet detach "wallet-name"
Message: Wallet successfully attached to blockchain.

**Comment by vincenthz** [comment]
thanks for the report, we accept PRs :)

**Comment by prographo** [comment]
wow, crazy, we reported the same thing almost at the same time. What is a PR? Is that where we fix the issue and submit the fix. Is there a document for that?

**Comment by NicolasDP** [comment]
There is documentations on github on how to propose a change (also called a Pull Request - **PR**) https://help.github.com/categories/collaborating-with-issues-and-pull-requests/

**Comment by Syr3mas** [comment]
@vincenthz Noted for the PR. I'll have a look a the docs @NicolasDP . Good to know others on the CLI @prographo .
