### ISSUE TITLE
`blockchain query` command

### ISSUE THREAD

**Issue by NicolasDP** [input-output-hk/cardano-byron-cli#55]
add a way to query the blockchain, the idea is to bootrstap the query mechanism with something rather simple and to build up from there.

The most needed type of queries are lookup for **addresses** and for **transaction ids**.

An example of the command would be to ask for expecific addresses and to return the list of block hash where we found occurrences of the useful values.

```
> cardano-cli blockchain query mainnet --address="Aa23456789abcdef..." --or --address="Aa210..."
abcedf...
0129345...
```

**Comment by mzabaluev** [comment]
An embryonic implementation is up for review in #70.
