### ISSUE TITLE
sign transaction with an offline wallet

### ISSUE THREAD

**Issue by NicolasDP** [input-output-hk/cardano-byron-cli#57]
currently it is not possible to sign the transaction with a wallet that does not have access to the network as it needs to know the unspent output (and the associated derivation path).

This is a follow up on issue discussed in #42

**Comment by xiewenlong1202** [comment]
can I construct inputs for a transaction and import it to the wallet and try to sign it offline?
As I can export a transaction from a wallet in any stage, I can know the form of a transaction.
I want to do the following step：
1. with online wallet A, I create a normal transaction and add inputs, outputs after that export the transaction, I got a constructed file
2. replace the field in the constructed file with my goal real inputs and outputs, and save the file
(the UTXOs and index can get from other source)
3. with offline wallet B, import the transaction. the UTXOs of the inputs are all wallet B's. and in wallet B, try to finalize the transaction and sign it. and export then send

Is this possible?

**Comment by xiewenlong1202** [comment]
did you have any check field in the transfer exported file? like a checksum or hash value that confirms the content not modified?
