### ISSUE TITLE
blockchain log causes a crash

### ISSUE THREAD

**Issue by amias-iohk** [input-output-hk/cardano-byron-cli#62]
**Platform:** Ubuntu 18.10 Linux i686 
**Version:** https://github.com/input-output-hk/cardano-cli/releases/tag/v1.0.0-alpha3

**Expected Behaviour:** cardano blockchain log should be printed and the program should exit.
**Actual Behaviour:** cardano blockchain log is printed by program crashes.

**Output:**

> RUST_BACKTRACE=1 ./cardano-cli blockchain log mainnet
>
> < snipped lots of hashes >
       65904a89e6d0e5f881513d1736945e051b76f095eca138ee869d543d
      af2800c124e599d6dec188a75f8bfde397ebb778163a18240371f2d1
>
> thread 'main' panicked at 'block location', libcore/option.rs:1000:5> 
   stack backtrace:
    0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
    1: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:227
             at libstd/panicking.rs:477
   3: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:391
   4: rust_begin_unwind
             at libstd/panicking.rs:326
   5: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   6: core::option::expect_failed
             at libcore/option.rs:1000
   7: <cardano_storage::iter::reverse::ReverseIter<'a> as core::iter::iterator::Iterator>::next
   8: cardano_cli::main
   9: std::rt::lang_start::{{closure}}
  10: main
  11: __libc_start_main
  12: <unknown>

Notes: 

- From a UX point of view It might help to have timestamps or some kind of sequence data with the hashes
- The blockchain seemed to be fully synced

**Comment by mzabaluev** [comment]
Backtrace from a debug build:

```
        65904a89e6d0e5f881513d1736945e051b76f095eca138ee869d543d
        af2800c124e599d6dec188a75f8bfde397ebb778163a18240371f2d1


thread 'main' panicked at 'block location', libcore/option.rs:1000:5
stack backtrace:
  ...
   9: <core::option::Option<T>>::expect
             at libcore/option.rs:312
  10: <cardano_storage::iter::reverse::ReverseIter<'a> as core::iter::iterator::Iterator>::next
             at cardano-deps/storage/src/iter/reverse.rs:39
  11: cardano_cli::blockchain::commands::log
             at src/blockchain/commands.rs:247
  12: cardano_cli::subcommand_blockchain
             at src/main.rs:356
  13: cardano_cli::main
             at src/main.rs:77
```

**Comment by gsovereignty** [comment]
Same behaviour on OSX
