### ISSUE TITLE
builds on Appveyor are not working

### ISSUE THREAD

**Issue by amias-iohk** [input-output-hk/cardano-byron-cli#67]
**Description**
Builds for cardano-cli have been failing on appveyor for several months.

**Data**
a build where this failed
https://ci.appveyor.com/project/vincenthz/cardano-cli/builds/20287440

another build with the session
https://ci.appveyor.com/project/vincenthz/cardano-cli/builds/18736307/job/s4m92wofd0hhkrf7

history of builds , only merges pass
https://ci.appveyor.com/project/vincenthz/cardano-cli/history

**Suggestions**
looks like the submodules might not be updated

**Comment by amias-iohk** [comment]
https://github.com/input-output-hk/rust-cardano/pull/387 seems to have fixed this , there seemed to be an error in the notifications section that was failing builds.   We might need to do some work later to speed up these builds as they take 3x5 each and appveyor is quite slow.

**Comment by NicolasDP** [comment]
No it is still not working. cardano-cli's branches and PRs are still failing to compile. Only master branch works so far. It might be an issue the ps1 script.
