### ISSUE TITLE
Daedalus wallet recovery: address payload of infinite size bug make cardano-cli crash

### ISSUE THREAD

**Issue by backuitist** [input-output-hk/cardano-byron-cli#73]
Running cardano-cli wallet sync mywallet
```
syncing wallet from 82.13 to 85.2368
⠙ [00:00:00] [###>------------------------------------] 6064/67155 (3s)
memory allocation of 18446744073709551613 bytes failed
```

Looks like a bit too much memory.

```
* wallet model RandomIndex2Levels
 * derivation scheme V1
 * synced to block  9eab5304cc7a5d8106606f99966b14f458e99798d38e547da37e30740a7936f2 (82.13)
```

**Comment by endline** [comment]
same issue on `mac os 10.13.6`

`stable-x86_64-apple-darwin`

**Comment by endline** [comment]
ill note that this **only** occurs when claiming then syncing a `daedalus` wallet.

running the below completes fine 👍 
```
cardano-cli wallet create <wallet>
cardano-cli wallet attach <wallet> mainnet
cardano-cli wallet sync wallet
```

**Comment by NicolasDP** [comment]
thanks, this is very valuable details. I think I can pin down a bit the problem now.

**Comment by endline** [comment]
@NicolasDP 👊

**Comment by NicolasDP** [comment]
the fix is in latest SDK, but I'll still need to update the cli now to utilise this fix.

**Comment by NicolasDP** [comment]
this has now been fixed

**Comment by endline** [comment]
fyi, after updating and rebuilding i still have the issue for my daedalus claimed wallet.
perhaps i am missing something?

**Comment by NicolasDP** [comment]
do you have the error:

```
Error while decoding an address' payload
```

**Comment by NicolasDP** [comment]
Ok I closed it because I thought the problem was that it was having a _panic_ when seeing the invalid addresses. But the actual problem is that it is impossible to retrieve an address beyond block [`bb1d04fc641b856f40a51f723251aa99a818dd395ca35436210aafafc165c1a7`](https://cardanoexplorer.com/slot/bb1d04fc641b856f40a51f723251aa99a818dd395ca35436210aafafc165c1a7) where there are addresses that are of invalid sizes.

**Comment by NicolasDP** [comment]
lastest commit should work fine now

**Comment by endline** [comment]
i still get the aforementioned

```
$ cardano-cli wallet sync EndlineWallet
...
syncing wallet from 82.13 to 90.18046
⠒ [00:00:02] [#>--------------------------------------] 6671/190833 (1m)
memory allocation of 18446744073709551613 bytes failedAbort trap: 6
```

now attempting a `detach` and re `attach` + `sync`

**Comment by endline** [comment]
hmm. no dice.

```
syncing wallet from 0.GENESIS to 90.18046
⠁ [00:13:45] [####################################>---] 1777389/1962046 (1m)
memory allocation of 18446744073709551613 bytes failedAbort trap: 6
```

**Comment by NicolasDP** [comment]
are you using the latest commit on master branch [`8b29bb892c7c9a9540148d42ec9fbcfaecc265ac`](https://github.com/input-output-hk/cardano-cli/commit/8b29bb892c7c9a9540148d42ec9fbcfaecc265ac) ?

**Comment by endline** [comment]
yes indeed.

```
$ git log -n 1
commit 8b29bb892c7c9a9540148d42ec9fbcfaecc265ac (HEAD -> master, origin/master, origin/HEAD)
Merge: 062eb13 47ab936
Author: Nicolas Di Prima <nicolas@primetype.co.uk>
Date:   Fri Dec 21 23:40:50 2018 +0000

    Merge pull request #86 from input-output-hk/ignore-invalid-addresses

    Ignore invalid addresses
```

**Comment by endline** [comment]
either way, this is no longer an issue for me personally. as i have moved on to other wallets.
yet more or less to get to the bottom of things.

**Comment by NicolasDP** [comment]
ok, thanks for the feedbacks. I cannot reproduce your error with the last changes.

**Comment by endline** [comment]
cool. thanks for ur efforts.
i will reply on this issue if i come up with a fix for this.

**Comment by gsovereignty** [comment]
I'm having the same issue with the current master branch.

`memory allocation of 18446744073709551613 bytes failed`

Do you want any backtrace or anything?

**Comment by mzabaluev** [comment]
Yes, please post the backtrace with `RUST_BACKTRACE=1` in the environment.
