### ISSUE TITLE
Circle Ci builds should use our own docker image

### ISSUE THREAD

**Issue by amias-iohk** [input-output-hk/cardano-byron-cli#95]
Motivation:
Our builds and tests have dependencies , these are currently be adding during jobs , we could be much more efficient if we installed them into a shared docker image.  

this is a good starting point 
https://hub.docker.com/r/circleci/rust/dockerfile

**Comment by mzabaluev** [comment]
It may be even worthwhile to have several custom images tailored for each significantly different job kind, though there is a tradeoff against the need to maintain multiple custom Docker images.

Furthermore, multiple images are a necessity when the official base image needs to be different, for example it should be (derived from) `rustlang/rust:nightly` for the nightly toolchain.
