### ISSUE TITLE
Sign a text (proof you own the address) 

### ISSUE THREAD

**Issue by yanik-ai** [input-output-hk/cardano-byron-cli#96]
I'm developing software for a Cardano pool, and I need some way to identify which account contributed to the pool.  

Therefore having a possibility to sign some text (proof you own the address) would be very helpful. Similar to feature Bitcoin has.  

Cheers

**Comment by NicolasDP** [comment]
Thanks for opening the issue. I am adding something similar to the CLI in de `debug` sub commands. This can only help you if you know the extended private key.

I will this open in case someone can pick this up to do something similar with the wallet command (`wallet sign <wallet-name> <account-idx> <address-idx>`).
