### ISSUE TITLE
Suggestion about installation instructions

### ISSUE THREAD

**Issue by gmanroney** [input-output-hk/cardano-byron-cli#98]
the first step of installation instructions is "install rust toolchain;"
can this be a link to where the rust toolchain installer can be found?

**Comment by NicolasDP** [comment]
It has been done earlier today in this [commit](https://github.com/input-output-hk/cardano-cli/commit/820386e682080f7aa43d9db122df1972d2ed71f6)

**Comment by gmanroney** [comment]
wow :-)
