### ISSUE TITLE
wallet sync command not working

### ISSUE THREAD

**Issue by Mercurial** [input-output-hk/cardano-byron-cli#99]
Hi guys

I try to issue these commands

`cardano-cli blockchain pull mainnet`

![image](https://user-images.githubusercontent.com/585569/52182120-c335bc80-2834-11e9-92ee-56e40a9ee074.png)

and then I sync my wallet to the blockchain

`cardano-cli wallet sync "My Wallet"`

![image](https://user-images.githubusercontent.com/585569/52182125-d5175f80-2834-11e9-8bcd-125f79d26e7d.png)

but it seems its not writing the updates to the wallet data file
![image](https://user-images.githubusercontent.com/585569/52182137-f11b0100-2834-11e9-8be2-36a83caddaaa.png)

its always stuck to the first point when i attached the wallet

but this is fixed when i detach / attach but then i get the error again, so it takes a very long time to get updates to the wallet by doing "detach/attach"

but maybe I'm doing something wrong.

OS: Windows Sub-System for Linux, Ubuntu 18

Thank you!

**Comment by NicolasDP** [comment]
Hi. The wallet will never really sync up to the last block. It will update to last block of interest. We noticed when writing this that it helps with performances. So unless there is a new epoch or you receive a new transaction it will remain to that block 99.12212.

**Comment by Mercurial** [comment]
> 
> 
> Hi. The wallet will never really sync up to the last block. It will update to last block of interest. We noticed when writing this that it helps with performances. So unless there is a new epoch or you receive a new transaction it will remain to that block 99.12212.

hello, first of all, thank you very much for the response. 

I understand this optimization is really great!

but I have tried it the 3rd time now

In my case I have this wallet with an address: 
`Ae2tdPwUPEYvwYJzqC6p4UP45N1b2xBw9ocTFc2UaMDCuQHjUBqpwUMgWEX`

https://cardanoexplorer.com/address/Ae2tdPwUPEYvwYJzqC6p4UP45N1b2xBw9ocTFc2UaMDCuQHjUBqpwUMgWEX

in Cardano explorer it confirms that I have received a total of 3 ADA

but in the cardano-cli wallet status it really won't update the balance

![image](https://user-images.githubusercontent.com/585569/52184405-bb364680-284d-11e9-84fd-71e13981fbf0.png)

but maybe I am missing something, may I know what steps would I need if I wanted to update the balance of my wallet?

**Comment by NicolasDP** [comment]
Hi thanks for the update.

I am sorry to hear you are having issues utilising the cardano-cli. I'm going to throw this now in case you have missed it.

1. can you give us the result of `cardano-cli --version` ?
2. when you are updating your balance, are you running this command `cardano-cli blockchain pull mainnet && cardano-cli wallet sync "My Wallet"` ?
3. pulling the blockchain and syncing the wallet does not show operation error : the program does exit successfully. However the output is not the expected one.

Now to be sure I have understood the problem in its entirety (I am assuming the response to the question above are satisfying so we can go a bit faster):

1. you have 3 transactions on your bip44 wallet;
    a. one at block 99.12212
    b. one at block 99.12684
    c. one at block 99.13237
2. the first sync showed you your first transaction, but the pulling the blockchain and then syncing the wallet didn't show the second transaction;
3. you detached and then attached the wallet to the blockchain, synced again and it then show the 2 transactions;
4. then you received the 3rd one, but you have the same issue again.

**Comment by Mercurial** [comment]
> 
> 
> Hi thanks for the update.
> 
> I am sorry to hear you are having issues utilising the cardano-cli. I'm going to throw this now in case you have missed it.
> 
>     1. can you give us the result of `cardano-cli --version` ?
> 
>     2. when you are updating your balance, are you running this command `cardano-cli blockchain pull mainnet && cardano-cli wallet sync "My Wallet"` ?
> 
>     3. pulling the blockchain and syncing the wallet does not show operation error : the program does exit successfully. However the output is not the expected one.
> 
> 
> Now to be sure I have understood the problem in its entirety (I am assuming the response to the question above are satisfying so we can go a bit faster):
> 
>     1. you have 3 transactions on your bip44 wallet;
>        a. one at block 99.12212
>        b. one at block 99.12684
>        c. one at block 99.13237
> 
>     2. the first sync showed you your first transaction, but the pulling the blockchain and then syncing the wallet didn't show the second transaction;
> 
>     3. you detached and then attached the wallet to the blockchain, synced again and it then show the 2 transactions;
> 
>     4. then you received the 3rd one, but you have the same issue again.

hey thank you very much for your patience,

you are completely correct

1.) Here is a screenshot
![image](https://user-images.githubusercontent.com/585569/52249441-22c3c300-292e-11e9-84c0-493a34efb804.png)

2.) yes thats correct

3.) Yes but balance is still stuck at  `99.12684`

![image](https://user-images.githubusercontent.com/585569/52249485-57d01580-292e-11e9-8b0e-528e11ddfe7c.png)

to add that before I issued the 3rd transaction I spawned a ubuntu 18 vps as I suspected the issue could've been because of Windows Subsystem for Linux (maybe incompatibility)

pulled the blockchain and synced the same wallet. 

Then I finaly sent the 3rd transaction and now both my WSL and VPS wallet are stuck in the same block. And won't show the updated balance. 

I could probably detach and attach both wallets to update though, but I believe this issue is still worth checking out

Thanks again 
@NicolasDP

**Comment by Mercurial** [comment]
Another update:

I sent my 4th transaction still stuck but I reset the wallet to sync up to the 3rd transaction. 

I successfully managed to build , sign and send a transaction back to main wallet. 

and try to sync with `cardano-cli blockchain pull mainnet && cardano-cli wallet sync "My Wallet"`

I am still stuck with the 3 transactions now and no records regarding the sent outputs.

I really think there is an issue with syncing on my side :(

```
99.12212 |8eaf4acf374ea0ed8e2ac216731ba5e04d61f5b467e44fdf2cbdd7f5d32f6cab.000|      1.000000|              
99.12684 |515c7bc3957bd1d0f947a740705bfa4d9a051d4d82403334632d3ecdbbcf2d47.000|      1.000000|              
99.13237 |c0b14bf25653ba9aeb19caafbca0f0ad688111c1218677a3d3bd582da259a2ba.001|      1.000000|  
```

Is there any possible work around I can do to sync in real time without refreshing the entire wallet(detach/attach)?

**Comment by NicolasDP** [comment]
@Mercurial thanks for checking all of this for us and reporting this issue.

So I can reproduce it on `testnet` (by the way there is the faucet here : https://testnet.iohkdev.io/cardano/faucet/ if you want to experiment with the CLI without wasting your Ada in fees).

**Comment by Mercurial** [comment]
hello @NicolasDP does this commit fix the issue?

**Comment by Mercurial** [comment]
Thank you @NicolasDP you are a hero!
